# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2.1
orbs:
  slack: circleci/slack@4.4.4
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - SLACK_SECRETS
jobs:
  build:
    docker:
      - image: cimg/node:17.0.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: brew install circlecicli 
      - run: circleci config validate
