# version: 2.1
# orbs:
#   python: circleci/python@2.1.1
#   heroku: circleci/heroku@1.2.6
#   browser-tools: circleci/browser-tools@1.4.1  

# commands:
#   update-submodules:
#     steps:
#       - run:
#           name: "Update Submodules"
#           command: |
#             git submodule sync --recursive
#             git submodule update --init --recursive


# jobs:
#   build_and_test: # this can be any name you choose
#     macos:
#       xcode: 14.3.0
#     resource_class: macos.x86.medium.gen2  
#     steps:
#       - checkout
#       - python/install-packages
# #       - browser-tools/install-chrome
# #       - browser-tools/install-chromedriver
# #       - run:
# #           command: |
# #             google-chrome --version
# #             chromedriver --version
# #           name: Check install          
# #       - run:
# #           name: Run tests
# #           command: pipenv run python manage.py test # alternatively run `python -m pytest` if you are running vanilla pytest
# #       - run:
# #           name: chmod webdrivers
# #           command: chmod +x /home/circleci/.webdrivers/chromedriver          
# #       - store_test_results:
# #           path: test-results
# #       - store_artifacts:
# #           path: test-results
# #           destination: tr1
# #       - persist_to_workspace:
# #           root: ~/project
# #           paths:
# #             - .
                     
#   test: # this can be any name you choose
#     docker:
#       - image: cimg/python:3.10.1
#     steps:
#       - run: echo "hello world"



#   deploy: # this can be any name you choose
#     docker:
#       - image: cimg/python:3.10.1
#     steps:
#       - attach_workspace:
#           at: ~/project
#       - heroku/deploy-via-git: 
#           force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git      



# workflows:
#   on_commit:
#     jobs:
#       - build_and_test
#       - test: 
#           requires:
#             - build_and_test            
#       - deploy: 
#           requires:
#             - test  
 


version: '2.1'
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    macos:
      xcode: 14.3.0
    resource_class: macos.x86.medium.gen2  
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: dev-requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pytest --version
          name: Test
workflows:
  main:
    jobs:
      - build

